### ISSUE TITLE
不忽略文件夹怎么设置

### ISSUE THREAD

**Issue by shenghuitu** [lal0ne/monitor#1]
要监控文件夹的生成，怎么设置

**Comment by lal0ne** [comment]
目前没有监控文件夹生成的配置，你可以注释以下代码，重新打包，默认会监控目录的生成
[修改位置](https://github.com/lal0ne/monitor/blob/master/lib/core.go#L12)
需要注释掉
```golang
if core.IsDir(evName) {
	return
}
```
